<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- <xacro:include filename="common_propertes.xacro" /> -->

    <xacro:property name="base_lenght" value="0.6"/>
    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.2"/>

    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_lenght" value="0.05"/>

    <!-- <xacro:macro name="example_macro" param="a b c">
        <link name="dummy_link">
            <visual>
                <geometry>
                    <box size="${a} ${b} ${c}" />
                </geometry>
            </visual>
        </link>
    </xacro:macro>

    <xacro:example_macro a="2" b="3" c="4" /> -->


    <link name="base_footpriint" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_lenght} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
            <material name="blue" />
        </visual>
    </link>

    <!-- wheel -->
    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_lenght}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2} 0 0" />
                <material name="gray" />
            </visual>
        </link>
    </xacro:macro>

    <link name="caster_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius / 2.0}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="gray" />
        </visual>
    </link>

    <xacro:wheel_link prefix="right" />
    <xacro:wheel_link prefix="left" />

    <!-- <link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_lenght}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2} 0 0" />
            <material name="gray" />
        </visual>
    </link>

    <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_lenght}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2} 0 0" />
            <material name="gray" />
        </visual>
    </link> -->

    <!-- joint -->
    <joint name="base_joint" type="fixed">
        <parent link="base_footpriint" />
        <child link="base_link" />  
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />      
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="${-base_lenght / 4.0} ${-(base_width + wheel_lenght) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="${-base_lenght / 4.0} ${(base_width + wheel_lenght) / 2.0} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link" />
        <origin xyz="${base_lenght / 3.0} 0 ${-wheel_radius / 2.0}" rpy="0 0 0" />
    </joint>
</robot>